spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Shivam@123
    url: jdbc:mysql://localhost:3306/boot
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
